template = "https://github.com/giellalt/template-lang-und"
rev_id = 278
template_sha = "58c9d1b66bc21da4ce588378206dd02d219954ae"

[replacements]
__GLOTTOLOG_ID__ = "umes1235"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-sju-x-sydlapsk"
__UND2C__ = "sju-x-sydlapsk"
__UNDEFINED__ = "18th century Southern Saami"
__UND__ = "sju-x-sydlapsk"
