template = "https://github.com/giellalt/template-lang-und"
rev_id = 272
template_sha = "f40ff07ea2383e4e83e8ad0ff88b795ceaf841e6"

[replacements]
__GLOTTOLOG_ID__ = "umes1235"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-sju-x-sydlapsk"
__UND2C__ = "sju-x-sydlapsk"
__UNDEFINED__ = "18th century Southern Saami"
__UND__ = "sju-x-sydlapsk"
